### ISSUE TITLE
启动后，客服和访客消息不互通

### ISSUE THREAD

**Issue by dayuanyuan1989** [taoshihan1991/go-fly#11]
版本: `v0.2.1-alpha`

启动命令

```bash
./go-fly.exe server -p 8084
```

访问url:  `http://127.0.0.1:8084/index`

在启动日志里也没看到任何获取message相关sql，说明的确没有访问message的行为被触发

看到路由里挂在的handler很奇怪，get_status和get_message触发的handler是同一个function

![image](https://user-images.githubusercontent.com/8370129/100339127-6bbd9d80-3014-11eb-93c4-a1d48c11633d.png)

![image](https://user-images.githubusercontent.com/8370129/100339332-b212fc80-3014-11eb-90a0-c1e09bf2791b.png)

**Comment by taoshihan1991** [comment]
获取最新的代码试试

**Comment by taoshihan1991** [comment]
稍等我重新发布一个包

**Comment by dayuanyuan1989** [comment]
wokr passed!
